apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: opa-exporter
  name: opa-exporter
  namespace: opa-exporter
  annotations:
    prometheus.io/scrape-slow: "true"
spec:
  ports:
  - name: 9141-9141
    port: 9141
    protocol: TCP
    targetPort: 9141
  selector:
    app: opa-exporter
  type: ClusterIP
status:
  loadBalancer: {}
